#!/usr/bin/env bash

if [[ "$OSTYPE" == "linux-gnu" ]]; then
    OS=linux-amzn
elif [[ "$OSTYPE" == "darwin"* ]]; then
    OS=darwin
else
    echo "Unhandled OS: '$OSTYPE'"
    exit 1
fi

# Check if the system has engineer installed, if not, use a local copy.
if ! type "engineer" > /dev/null; then
    # Setup Prisma engine build & test tool (engineer).
    set -e
    curl --fail -sSL "https://prisma-engineer.s3-eu-west-1.amazonaws.com/signatures_checksums/621bb310ca49b1c2f941ea71137f63fe44c62847/linux-amzn/engineer.gz" --output engineer.gz
    gzip -d engineer.gz
    chmod +x engineer

    # Execute passed command and clean up
    ./engineer $@
    rm -rf ./engineer
else
    # Already installed on the system
    set -e
    engineer $@
fi