[package]
name = "query-engine"
version = "0.1.0"
authors = ["Dominic Petrick <dompetrick@gmail.com>", "Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

[lib]
name = "query_engine"

[features]
default = ["sql", "graphql"]
sql = ["sql-connector"]
graphql = ["graphql-parser"]

[dependencies]
futures = "0.3"
http = "0.2"
hyper = "0.13"
tokio = { version = "=0.2.13", features = ["rt-threaded", "macros"] }

async-trait = "0.1"
prisma-inflector = { path = "../../libs/prisma-inflector" }
datamodel = { path = "../../libs/datamodel/core" }
prisma-models = { path = "../../libs/prisma-models" }
query-core = { path = "../core" }
connector = { path = "../connectors/query-connector", package = "query-connector" }
sql-connector = { path = "../connectors/sql-query-connector", optional = true, package = "sql-query-connector" }
graphql-parser = { git = "https://github.com/prisma/graphql-parser", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = [ "preserve_order" ] }
base64 = "0.10"
rust-embed = { version = "5.2" }
failure = { version = "0.1" }
indexmap = { version = "1.0", features = [ "serde-1" ] }
itertools = "0.8"
url = "2.1"
structopt = "0.3"
rust_decimal = "=1.1.0"
once_cell = "1.3"

tracing = "0.1"
tracing-subscriber = { version = "0.2", features = ["json"] }
tracing-attributes = "0.1"

user-facing-errors = { path = "../../libs/user-facing-errors" }
pretty_assertions = "0.6.1"
tracing-futures = "0.2.3"

[build-dependencies]
rustc_version = "0.2.3"

[dev-dependencies]
test-macros = { path = "../../libs/test-macros" }
test-setup = { path = "../../libs/test-setup" }
quaint = { git = "https://github.com/prisma/quaint", features = ["full", "tracing-log"] }
migration-connector = { path = "../../migration-engine/connectors/migration-connector" }
migration-core = { path = "../../migration-engine/core" }
introspection-core = { path = "../../introspection-engine/core" }
sql-migration-connector = { path = "../../migration-engine/connectors/sql-migration-connector" }
indoc = "0.3"
anyhow = "1"
serial_test = "*"
